### ISSUE TITLE
Swagger API warning?

### ISSUE THREAD

**Issue by gliptak** [controlm/controlm.github.io#1]
The Swagger site

https://github.com/controlm/controlm.github.io/blob/master/index.html#L350

is referenced by IP and also shows an HTTPS warning. Could those be updated?

Thanks

**Comment by Galgc** [comment]
The swagger site was updated to http://aapi-swagger-doc.s3-website-us-west-2.amazonaws.com/ and no longer shows the HTTPS warning.
